apiVersion: apps/v1
kind: Deployment
metadata:
  name: realfood-clients-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realfood-clients-app
  template:
    metadata:
      labels:
        app: realfood-clients-app
    spec:
      containers:
      - env:
        - name: DATABASE_DB
          value: "realfood-clients"
        - name: DATABASE_HOST
          value: "realfood-clients-postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: RABBITMQ_HOST
          value: "realfood-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: JWT_SECRET
          value: "a2ffb28f-23ec-4939-b2b3-c966de6a751d"
        - name: RESTAURANT_HOST
          value: "realfood-restaurants-service"
        - name: RESTAURANT_PORT
          value: "8081"
        image: cloudappsteam/es.urjc.realfood.clients:1.3.0
        imagePullPolicy: IfNotPresent
        name: "realfood-clients"
        ports:
        - containerPort: 8081
      restartPolicy: Always
