apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqldbclients-pv-claim
  labels:
    app: sqldbclients
spec:
  storageClassName: "sqldbclients-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi