version: "3"
services:
  clients:
    container_name: realfoodclients
    image: cloudappsteam/es.urjc.realfood.clients:1.2.0
    environment:
      - DATABASE_HOST=sqldbclients
      - DATABASE_PORT=5432
      - DATABASE_DB=realfood-clients
    ports:
      - "8080:8081"
  sqldbclients:
    container_name: sqldbclients
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=realfood-clients
    expose:
      - "5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.14-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    expose:
      - "5672"
      - "15672"